In [ ]:
#import data csv dari lokal
import pandas as pd
df_data = pd.read_csv(r'D:\Michael Road To Data Analyst\Dataset\SampleSuperstore.csv')
df_data.head()

,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub-Category,Sales,Quantity,Discount,Profit
0,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,261.9600,2,0.00,41.9136
1,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,731.9400,3,0.00,219.5820
2,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,14.6200,2,0.00,6.8714
3,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,957.5775,5,0.45,-383.0310
4,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,22.3680,2,0.20,2.5164

In [ ]:
#Membuat data frame baru dan belajar untuk menggabungkan data frame dengan merge
df_baru = pd.DataFrame({'Region': ['Central', 'East', 'South', 'West'],
                        'Region_Manager': ['John Smith', 'Jane Doe', 'Michael Johnson', 'Emily Davis']})
gabungan_df = pd.merge(df_data, df_baru, on='Region', how='left')
print(gabungan_df)

           Ship Mode    Segment        Country             City       State  \
0       Second Class   Consumer  United States        Henderson    Kentucky
1       Second Class   Consumer  United States        Henderson    Kentucky
2       Second Class  Corporate  United States      Los Angeles  California
3     Standard Class   Consumer  United States  Fort Lauderdale     Florida
4     Standard Class   Consumer  United States  Fort Lauderdale     Florida
...              ...        ...            ...              ...         ...
9989    Second Class   Consumer  United States            Miami     Florida
9990  Standard Class   Consumer  United States       Costa Mesa  California
9991  Standard Class   Consumer  United States       Costa Mesa  California
9992  Standard Class   Consumer  United States       Costa Mesa  California
9993    Second Class   Consumer  United States      Westminster  California

      Postal Code Region         Category Sub-Category     Sales  Quantity  \
0           42420  South        Furniture    Bookcases  261.9600         2
1           42420  South        Furniture       Chairs  731.9400         3
2           90036   West  Office Supplies       Labels   14.6200         2
3           33311  South        Furniture       Tables  957.5775         5
4           33311  South  Office Supplies      Storage   22.3680         2
...           ...    ...              ...          ...       ...       ...
9989        33180  South        Furniture  Furnishings   25.2480         3
9990        92627   West        Furniture  Furnishings   91.9600         2
9991        92627   West       Technology       Phones  258.5760         2
9992        92627   West  Office Supplies        Paper   29.6000         4
9993        92683   West  Office Supplies   Appliances  243.1600         2

      Discount    Profit   Region_Manager
0         0.00   41.9136  Michael Johnson
1         0.00  219.5820  Michael Johnson
2         0.00    6.8714      Emily Davis
3         0.45 -383.0310  Michael Johnson
4         0.20    2.5164  Michael Johnson
...        ...       ...              ...
9989      0.20    4.1028  Michael Johnson
9990      0.00   15.6332      Emily Davis
9991      0.20   19.3932      Emily Davis
9992      0.00   13.3200      Emily Davis
9993      0.00   72.9480      Emily Davis

[9994 rows x 14 columns]

In [ ]:
#Belajar menggabungkan data frame secara bertumpuk dengan concat
tabel_1 = gabungan_df.iloc[:4996]
print(tabel_1)
tabel_2 = gabungan_df.iloc[4996:]
print(tabel_2)
gabung_lagi = pd.concat([tabel_1, tabel_2])
print(gabung_lagi)

           Ship Mode      Segment        Country             City       State  \
0       Second Class     Consumer  United States        Henderson    Kentucky
1       Second Class     Consumer  United States        Henderson    Kentucky
2       Second Class    Corporate  United States      Los Angeles  California
3     Standard Class     Consumer  United States  Fort Lauderdale     Florida
4     Standard Class     Consumer  United States  Fort Lauderdale     Florida
...              ...          ...            ...              ...         ...
4991  Standard Class    Corporate  United States          Chicago    Illinois
4992  Standard Class    Corporate  United States          Memphis   Tennessee
4993  Standard Class    Corporate  United States          Memphis   Tennessee
4994  Standard Class    Corporate  United States          Memphis   Tennessee
4995  Standard Class  Home Office  United States    New York City    New York

      Postal Code   Region         Category Sub-Category      Sales  Quantity  \
0           42420    South        Furniture    Bookcases   261.9600         2
1           42420    South        Furniture       Chairs   731.9400         3
2           90036     West  Office Supplies       Labels    14.6200         2
3           33311    South        Furniture       Tables   957.5775         5
4           33311    South  Office Supplies      Storage    22.3680         2
...           ...      ...              ...          ...        ...       ...
4991        60653  Central  Office Supplies      Binders  1889.9900         5
4992        38109    South  Office Supplies    Envelopes    55.9360         8
4993        38109    South  Office Supplies       Labels    18.4320         8
4994        38109    South        Furniture  Furnishings    20.3200         5
4995        10011     East  Office Supplies      Binders    52.0640         4

      Discount     Profit   Region_Manager
0         0.00    41.9136  Michael Johnson
1         0.00   219.5820  Michael Johnson
2         0.00     6.8714      Emily Davis
3         0.45  -383.0310  Michael Johnson
4         0.20     2.5164  Michael Johnson
...        ...        ...              ...
4991      0.80 -2929.4845       John Smith
4992      0.20    18.8784  Michael Johnson
4993      0.20     5.9904  Michael Johnson
4994      0.20     3.5560  Michael Johnson
4995      0.20    18.8732         Jane Doe

[4996 rows x 14 columns]
           Ship Mode      Segment        Country         City           State  \
4996  Standard Class    Corporate  United States      Raleigh  North Carolina
4997  Standard Class    Corporate  United States      Raleigh  North Carolina
4998  Standard Class  Home Office  United States  Los Angeles      California
4999  Standard Class  Home Office  United States  Los Angeles      California
5000  Standard Class  Home Office  United States  Los Angeles      California
...              ...          ...            ...          ...             ...
9989    Second Class     Consumer  United States        Miami         Florida
9990  Standard Class     Consumer  United States   Costa Mesa      California
9991  Standard Class     Consumer  United States   Costa Mesa      California
9992  Standard Class     Consumer  United States   Costa Mesa      California
9993    Second Class     Consumer  United States  Westminster      California

      Postal Code Region         Category Sub-Category    Sales  Quantity  \
4996        27604  South  Office Supplies   Appliances   48.784         1
4997        27604  South  Office Supplies      Binders   13.092         4
4998        90045   West       Technology       Phones  109.592         1
4999        90045   West  Office Supplies        Paper   56.700         5
5000        90004   West       Technology  Accessories   79.990         1
...           ...    ...              ...          ...      ...       ...
9989        33180  South        Furniture  Furnishings   25.248         3
9990        92627   West        Furniture  Furnishings   91.960         2
9991        92627   West       Technology       Phones  258.576         2
9992        92627   West  Office Supplies        Paper   29.600         4
9993        92683   West  Office Supplies   Appliances  243.160         2

      Discount   Profit   Region_Manager
4996       0.2   3.6588  Michael Johnson
4997       0.7 -10.0372  Michael Johnson
4998       0.2   8.2194      Emily Davis
4999       0.0  27.7830      Emily Davis
5000       0.0  28.7964      Emily Davis
...        ...      ...              ...
9989       0.2   4.1028  Michael Johnson
9990       0.0  15.6332      Emily Davis
9991       0.2  19.3932      Emily Davis
9992       0.0  13.3200      Emily Davis
9993       0.0  72.9480      Emily Davis

[4998 rows x 14 columns]
           Ship Mode    Segment        Country             City       State  \
0       Second Class   Consumer  United States        Henderson    Kentucky
1       Second Class   Consumer  United States        Henderson    Kentucky
2       Second Class  Corporate  United States      Los Angeles  California
3     Standard Class   Consumer  United States  Fort Lauderdale     Florida
4     Standard Class   Consumer  United States  Fort Lauderdale     Florida
...              ...        ...            ...              ...         ...
9989    Second Class   Consumer  United States            Miami     Florida
9990  Standard Class   Consumer  United States       Costa Mesa  California
9991  Standard Class   Consumer  United States       Costa Mesa  California
9992  Standard Class   Consumer  United States       Costa Mesa  California
9993    Second Class   Consumer  United States      Westminster  California

      Postal Code Region         Category Sub-Category     Sales  Quantity  \
0           42420  South        Furniture    Bookcases  261.9600         2
1           42420  South        Furniture       Chairs  731.9400         3
2           90036   West  Office Supplies       Labels   14.6200         2
3           33311  South        Furniture       Tables  957.5775         5
4           33311  South  Office Supplies      Storage   22.3680         2
...           ...    ...              ...          ...       ...       ...
9989        33180  South        Furniture  Furnishings   25.2480         3
9990        92627   West        Furniture  Furnishings   91.9600         2
9991        92627   West       Technology       Phones  258.5760         2
9992        92627   West  Office Supplies        Paper   29.6000         4
9993        92683   West  Office Supplies   Appliances  243.1600         2

      Discount    Profit   Region_Manager
0         0.00   41.9136  Michael Johnson
1         0.00  219.5820  Michael Johnson
2         0.00    6.8714      Emily Davis
3         0.45 -383.0310  Michael Johnson
4         0.20    2.5164  Michael Johnson
...        ...       ...              ...
9989      0.20    4.1028  Michael Johnson
9990      0.00   15.6332      Emily Davis
9991      0.20   19.3932      Emily Davis
9992      0.00   13.3200      Emily Davis
9993      0.00   72.9480      Emily Davis

[9994 rows x 14 columns]

In [ ]:
#Belajar membuat pivot table
sales_by_region = pd.pivot_table(gabung_lagi, index = 'Region', values = 'Sales', aggfunc = 'sum')
print(sales_by_region)
profit_by_category = pd.pivot_table(gabung_lagi, index = 'Category', values = 'Profit', aggfunc = 'sum')
print(profit_by_category)
volume_of_transaction_by_segment = pd.pivot_table(gabung_lagi, index = 'Segment', values = 'Sales', aggfunc = 'count')
print(volume_of_transaction_by_segment)

               Sales
Region
Central  501239.8908
East     678781.2400
South    391721.9050
West     725457.8245
                      Profit
Category
Furniture         18451.2728
Office Supplies  122490.8008
Technology       145454.9481
             Sales
Segment
Consumer      5191
Corporate     3020
Home Office   1783

In [ ]:
#Belajar mendeteksi missing value
df_data.Quantity = df_data.Quantity.replace(2,None)
df_data.isnull().sum()

Ship Mode          0
Segment            0
Country            0
City               0
State              0
Postal Code        0
Region             0
Category           0
Sub-Category       0
Sales              0
Quantity        2402
Discount           0
Profit             0
dtype: int64

In [ ]:
#Belajar mengisi missing value dengan metode fillna
df_data.Quantity = df_data.Quantity.fillna(2)
df_data.isnull().sum()

Ship Mode       0
Segment         0
Country         0
City            0
State           0
Postal Code     0
Region          0
Category        0
Sub-Category    0
Sales           0
Quantity        0
Discount        0
Profit          0
dtype: int64

In [ ]:
#Belajar mengelompokkan data dengan groupby
df_data.groupby(['Ship Mode', 'Segment'])['Profit'].agg(['sum', 'mean', 'count'])

                                   sum       mean  count
Ship Mode      Segment
First Class    Consumer     21374.0436  27.794595    769
               Corporate    14464.4724  29.823654    485
               Home Office  13131.3239  46.237056    284
Same Day       Consumer      9874.2054  31.148913    317
               Corporate     1818.1418  15.948612    114
               Home Office   4199.4117  37.494747    112
Second Class   Consumer     24946.9112  24.457756   1020
               Corporate    18225.7131  29.927279    609
               Home Office  14274.0111  45.170921    316
Standard Class Consumer     77924.0490  25.259011   3085
               Corporate    57470.8067  31.716781   1812
               Home Office  28693.9318  26.791720   1071